# Generated by Django 6.0.5 on 2026-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0006_packingboxitem_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50, unique=True, verbose_name='Mã xuất hàng')),
                ('export_date', models.DateField(verbose_name='Ngày xuất')),
                ('export_time', models.TimeField(blank=True, null=True, verbose_name='Giờ xuất')),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã khách hàng')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách hàng')),
                ('vehicle_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xe vận chuyển')),
                ('container_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã container')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tài xế')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('boxes', models.ManyToManyField(related_name='export_shipments', to='production.packingbox', verbose_name='Danh sách thùng')),
            ],
            options={
                'verbose_name': 'Phiếu xuất hàng',
                'verbose_name_plural': 'Phiếu xuất hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
