# Generated by Django 6.0.5 on 2026-05-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=50, unique=True, verbose_name='Mã lô')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị tính')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhà cung cấp')),
                ('received_date', models.DateField(verbose_name='Ngày nhập')),
                ('received_time', models.TimeField(blank=True, null=True, verbose_name='Giờ nhập')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='Số lượng nhập')),
                ('delivery_type', models.CharField(blank=True, choices=[('supplier_delivery', 'Nhà cung cấp giao'), ('company_pickup', 'Nhân viên công ty đi lấy'), ('retail_delivery', 'Khách lẻ giao'), ('other', 'Khác')], max_length=50, null=True, verbose_name='Hình thức giao nhận')),
                ('delivered_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người giao hàng')),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đi lấy hàng')),
                ('vehicle_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thông tin xe')),
                ('quality_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tình trạng hoa lúc nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='trace_qr/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Lô truy xuất',
                'verbose_name_plural': 'Lô truy xuất',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import_raw', 'Nhập kho nguyên liệu'), ('move_to_processing', 'Xuất đi sơ chế'), ('processing_done', 'Nhập kho thành phẩm'), ('processing_waste', 'Xả/hủy khi sơ chế'), ('export_order', 'Xuất cho đơn hàng'), ('packing', 'Đóng gói'), ('move_to_sale', 'Chuyển kho sale'), ('destroy', 'Hủy hoa'), ('adjust', 'Điều chỉnh'), ('other', 'Khác')], max_length=100, verbose_name='Hành động')),
                ('from_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Từ khu vực')),
                ('to_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đến khu vực')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhân viên thực hiện')),
                ('related_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã liên quan')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='traceability.tracelot', verbose_name='Mã lô')),
            ],
            options={
                'verbose_name': 'Nhật ký truy xuất',
                'verbose_name_plural': 'Nhật ký truy xuất',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng hủy')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do hủy')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người hủy')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian hủy')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='traceability.tracelot', verbose_name='Mã lô')),
            ],
            options={
                'verbose_name': 'Phiếu hủy hoa',
                'verbose_name_plural': 'Phiếu hủy hoa',
                'ordering': ['-created_at'],
            },
        ),
    ]
