# Generated by Django 6.0.5 on 2026-06-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_code', models.CharField(max_length=80, unique=True, verbose_name='Mã bó QR')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_stems', models.FloatField(default=0, verbose_name='Số cành ban đầu')),
                ('remaining_stems', models.FloatField(default=0, verbose_name='Số cành còn lại')),
                ('status', models.CharField(choices=[('raw', 'Nguyên liệu'), ('processing', 'Đang sơ chế'), ('processed', 'Đã sơ chế'), ('finished', 'Thành phẩm'), ('packed', 'Đã đóng gói'), ('exported', 'Đã xuất hàng'), ('damaged', 'Hủy/hao hụt')], default='raw', max_length=30, verbose_name='Trạng thái bó')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='trace_bundle_qr/', verbose_name='QR bó')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='traceability.tracelot', verbose_name='Mã lô')),
            ],
            options={
                'verbose_name': 'Bó QR truy xuất',
                'verbose_name_plural': 'Bó QR truy xuất',
                'ordering': ['lot', 'bundle_code'],
            },
        ),
    ]
