# Generated by Django 6.0.5 on 2026-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_tracebundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracebundle',
            options={},
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='actual_stems',
            field=models.FloatField(default=0, verbose_name='Số cành thực nhận/bó'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='bundle_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Số thứ tự bó'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='expected_stems',
            field=models.FloatField(default=0, verbose_name='Số cành dự kiến/bó'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú bó'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người bán/khách lẻ'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SĐT người bán'),
        ),
        migrations.AddField(
            model_name='tracebundle',
            name='source_type',
            field=models.CharField(choices=[('purchase', 'Đơn đặt mua'), ('walk_in', 'Khách lẻ mang tới'), ('adjustment', 'Nhập điều chỉnh')], default='purchase', max_length=30, verbose_name='Nguồn nhập'),
        ),
    ]
