# Generated by Django 6.0.5 on 2026-06-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0003_alter_tracebundle_options_tracebundle_actual_stems_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracebundle',
            options={'ordering': ['lot', 'product_code', 'bundle_number'], 'verbose_name': 'Bó QR truy xuất', 'verbose_name_plural': 'Bó QR truy xuất'},
        ),
        migrations.AlterUniqueTogether(
            name='tracebundle',
            unique_together={('lot', 'product_code', 'bundle_number')},
        ),
    ]
