# Generated by Django 6.0.5 on 2026-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=50, unique=True, verbose_name='Mã NV')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('gioi_tinh', models.CharField(blank=True, max_length=20, null=True, verbose_name='Giới tính')),
                ('sdt', models.CharField(blank=True, max_length=30, null=True, verbose_name='SĐT')),
                ('bo_phan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bộ phận')),
                ('chuc_vu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('dia_chi', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('ngay_vao_lam', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('trang_thai', models.CharField(default='Đang làm', max_length=50, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Danh sách nhân sự',
                'db_table': 'employees_employee',
                'ordering': ['ho_ten'],
            },
        ),
    ]
