# Generated by Django 6.0.5 on 2026-05-22 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu sơ chế')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Mã NV')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('employee_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giờ bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ hoàn thành')),
                ('total_hours', models.FloatField(default=0, verbose_name='Số giờ sơ chế')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu sơ chế',
                'verbose_name_plural': 'Phiếu sơ chế',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_stock_id', models.IntegerField(blank=True, null=True, verbose_name='ID tồn kho nguyên liệu')),
                ('product_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nhóm hàng')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='ĐVT')),
                ('flower_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NCC')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên NCC')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhập gốc')),
                ('soaking_days', models.IntegerField(default=0, verbose_name='Thời gian ngâm')),
                ('stock_quantity', models.FloatField(default=0, verbose_name='Tồn kho lúc sơ chế')),
                ('received_quantity', models.FloatField(default=0, verbose_name='Số lượng đã nhận')),
                ('bunch_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Loại cành/bó')),
                ('stems_per_bunch', models.IntegerField(default=0, verbose_name='Số cành/bó')),
                ('processed_stems', models.FloatField(default=0, verbose_name='Số cành sơ chế')),
                ('damaged_stems', models.FloatField(default=0, verbose_name='Số cành xả/hủy')),
                ('odd_stems', models.FloatField(default=0, verbose_name='Số cành lẻ')),
                ('extra_stems', models.FloatField(default=0, verbose_name='Số cành thừa')),
                ('final_stems', models.FloatField(default=0, verbose_name='Tổng cành thành phẩm')),
                ('final_bunches', models.FloatField(default=0, verbose_name='Số bó thành phẩm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='processing.processingticket', verbose_name='Phiếu sơ chế')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu sơ chế',
                'verbose_name_plural': 'Chi tiết phiếu sơ chế',
            },
        ),
    ]
