# Generated by Django 6.0.5 on 2026-05-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_add_missing_item_columns_2'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingticketitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_items', to='traceability.tracelot', verbose_name='Mã lô truy xuất'),
        ),
    ]
