# Generated by Django 6.0.5 on 2026-05-31 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_processingticketitem_lot'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooseStemMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_code', models.CharField(max_length=50, unique=True, verbose_name='Mã ghép bó')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('stems_per_bunch', models.IntegerField(default=0, verbose_name='Số cành/bó')),
                ('total_stems', models.FloatField(default=0, verbose_name='Tổng cành ghép')),
                ('total_bunches', models.FloatField(default=0, verbose_name='Tổng bó tạo được')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người ghép')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_loose_merges', to='traceability.tracelot', verbose_name='Lô chính (Lô được bù)')),
            ],
            options={
                'verbose_name': 'Phiếu ghép cành lẻ',
                'verbose_name_plural': 'Phiếu ghép cành lẻ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LooseStemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('product_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nhóm hàng')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NCC')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên NCC')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NV sơ chế')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhân viên sơ chế')),
                ('stems_per_bunch', models.IntegerField(default=0, verbose_name='Số cành/bó')),
                ('original_quantity', models.FloatField(default=0, verbose_name='Số cành lẻ ban đầu')),
                ('remaining_quantity', models.FloatField(default=0, verbose_name='Số cành lẻ còn lại')),
                ('status', models.CharField(choices=[('available', 'Còn cành lẻ'), ('used', 'Đã dùng hết'), ('expired', 'Quá ngày/Hủy')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_stem_stocks', to='traceability.tracelot', verbose_name='Mã lô truy xuất')),
                ('processing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_stems', to='processing.processingticketitem', verbose_name='Chi tiết sơ chế')),
            ],
            options={
                'verbose_name': 'Khay cành lẻ',
                'verbose_name_plural': 'Khay cành lẻ',
                'ordering': ['product_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LooseStemMergeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_used', models.FloatField(default=0, verbose_name='Số cành đã dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_merge_items', to='traceability.tracelot', verbose_name='Mã lô truy xuất nguồn')),
                ('merge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='processing.loosestemmerge', verbose_name='Phiếu ghép')),
                ('loose_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_items', to='processing.loosestemstock', verbose_name='Nguồn cành lẻ')),
            ],
            options={
                'verbose_name': 'Chi tiết ghép cành lẻ',
                'verbose_name_plural': 'Chi tiết ghép cành lẻ',
            },
        ),
    ]
