# Generated by Django 6.0.5 on 2026-05-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_loosestemmerge_loosestemstock_loosestemmergeitem'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loosestemmerge',
            name='main_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_loose_merges', to='traceability.tracelot', verbose_name='Lô chính'),
        ),
    ]
