# Generated by Django 6.0.5 on 2026-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_alter_loosestemmerge_main_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loosestemstock',
            name='carry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày chuyển cành lẻ'),
        ),
        migrations.AddField(
            model_name='loosestemstock',
            name='is_carried_next_day',
            field=models.BooleanField(default=False, verbose_name='Cành lẻ chuyển qua ngày sau'),
        ),
    ]
