# Generated by Django 6.0.5 on 2026-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_loosestemstock_carry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingticket',
            name='overtime_hours',
            field=models.FloatField(default=0, verbose_name='Số giờ tăng ca'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift1_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ca 1 - Kết thúc'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift1_hours',
            field=models.FloatField(default=0, verbose_name='Số giờ ca 1'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift1_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ca 1 - Bắt đầu'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift2_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ca 2 - Kết thúc'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift2_hours',
            field=models.FloatField(default=0, verbose_name='Số giờ ca 2'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='shift2_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ca 2 - Bắt đầu'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='total_work_hours',
            field=models.FloatField(default=0, verbose_name='Tổng giờ làm việc'),
        ),
        migrations.AddField(
            model_name='processingticket',
            name='work_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú thời gian làm việc'),
        ),
    ]
