# Generated by Django 6.0.5 on 2026-06-04 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_processingticket_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingticket',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ / ngày báo cáo sơ chế'),
        ),
    ]
