# Generated by Django 6.0.5 on 2026-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_processingticket_business_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingticketitem',
            name='compensate_stems',
            field=models.FloatField(default=0, verbose_name='Bù cành lẻ khác'),
        ),
    ]
