# Generated by Django 6.0.5 on 2026-05-24 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=50, verbose_name='Mã thùng')),
                ('box_number', models.IntegerField(default=1, verbose_name='Số thứ tự thùng')),
                ('total_bunches', models.FloatField(default=0, verbose_name='Tổng bó')),
                ('total_stems', models.FloatField(default=0, verbose_name='Tổng cành')),
                ('nw', models.FloatField(default=0, verbose_name='NW')),
                ('gw', models.FloatField(default=0, verbose_name='GW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thùng đóng gói',
                'verbose_name_plural': 'Thùng đóng gói',
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('flower_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tone/Nhóm')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='DVT')),
                ('standard_quantity', models.FloatField(default=0, verbose_name='SL tiêu chuẩn')),
                ('sale_quantity', models.FloatField(default=0, verbose_name='SL sale')),
                ('required_quantity', models.FloatField(default=0, verbose_name='Tổng số lượng cần')),
                ('finished_available', models.FloatField(default=0, verbose_name='Tồn thành phẩm lúc nhận')),
                ('missing_quantity', models.FloatField(default=0, verbose_name='Số lượng thiếu')),
                ('raw_available', models.FloatField(default=0, verbose_name='Tồn nguyên liệu')),
                ('need_processing_quantity', models.FloatField(default=0, verbose_name='Cần sơ chế thêm')),
                ('warning_note', models.TextField(blank=True, null=True, verbose_name='Cảnh báo sản xuất')),
                ('is_sale_item', models.BooleanField(default=False, verbose_name='Hàng sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_items', to='orders.orderitem', verbose_name='Sản phẩm đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết lệnh sản xuất',
                'verbose_name_plural': 'Chi tiết lệnh sản xuất',
            },
        ),
        migrations.CreateModel(
            name='PackingBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('bunches', models.FloatField(default=0, verbose_name='Số bó')),
                ('stems', models.FloatField(default=0, verbose_name='Số cành')),
                ('stems_per_bunch', models.FloatField(default=0, verbose_name='Cành/bó')),
                ('nw', models.FloatField(default=0, verbose_name='NW')),
                ('gw', models.FloatField(default=0, verbose_name='GW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.packingbox', verbose_name='Thùng')),
                ('production_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='production.productionitem', verbose_name='Sản phẩm sản xuất')),
            ],
            options={
                'verbose_name': 'Chi tiết thùng',
                'verbose_name_plural': 'Chi tiết thùng',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản xuất')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Khách hàng')),
                ('order_code', models.CharField(max_length=50, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('waiting', 'Chờ sản xuất'), ('processing', 'Đang sản xuất'), ('packing', 'Đang đóng gói'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ')], default='waiting', max_length=20, verbose_name='Trạng thái sản xuất')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú sản xuất')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian nhận đơn')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu sản xuất')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_order', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lệnh sản xuất',
                'verbose_name_plural': 'Lệnh sản xuất',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionitem',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionorder', verbose_name='Lệnh sản xuất'),
        ),
        migrations.AddField(
            model_name='packingbox',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='production.productionorder', verbose_name='Lệnh sản xuất'),
        ),
    ]
