# Generated by Django 6.0.5 on 2026-05-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_flowertype_box_type_flowertype_box_weight_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingBoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_bunches', models.IntegerField(default=0)),
                ('max_stems', models.IntegerField(default=0)),
                ('box_weight', models.FloatField(default=1.4)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loại thùng',
                'verbose_name_plural': 'Loại thùng',
            },
        ),
        migrations.CreateModel(
            name='PackingStemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('stems_quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quy cách bó',
                'verbose_name_plural': 'Quy cách bó',
            },
        ),
        migrations.CreateModel(
            name='ProductPackingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunches_per_box', models.IntegerField(default=0)),
                ('nw_per_bunch', models.FloatField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rules', to='production.packingboxtype')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_rules', to='categories.flowertype')),
                ('stem_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rules', to='production.packingstemrule')),
            ],
            options={
                'verbose_name': 'Quy chuẩn đóng gói',
                'verbose_name_plural': 'Quy chuẩn đóng gói',
            },
        ),
    ]
