# Generated by Django 6.0.5 on 2026-05-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_flowertype_box_type_flowertype_box_weight_and_more'),
        ('production', '0002_packingboxtype_packingstemrule_productpackingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã thùng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thùng')),
                ('capacity_index', models.FloatField(default=0, verbose_name='Chỉ số sức chứa')),
                ('box_weight', models.FloatField(default=1.4, verbose_name='Trọng lượng thùng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Sức chứa thùng',
                'verbose_name_plural': 'Sức chứa thùng',
            },
        ),
        migrations.CreateModel(
            name='PackingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_index', models.FloatField(default=0, verbose_name='Chỉ số đóng thùng')),
                ('base_stems', models.FloatField(default=50, verbose_name='Số cành quy đổi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_indexes', to='categories.flowertype', verbose_name='Loại hoa')),
            ],
            options={
                'verbose_name': 'Chỉ số đóng thùng',
                'verbose_name_plural': 'Chỉ số đóng thùng',
            },
        ),
    ]
