# Generated by Django 6.0.5 on 2026-05-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_boxcapacity_packingindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingbox',
            name='box_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_boxes', to='production.boxcapacity', verbose_name='Loại thùng'),
        ),
        migrations.AddField(
            model_name='packingbox',
            name='capacity_index',
            field=models.FloatField(default=0, verbose_name='Sức chứa thùng'),
        ),
        migrations.AddField(
            model_name='packingbox',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('full', 'FULL'), ('lack', 'THIẾU'), ('over', 'THỪA')], default='draft', max_length=20, verbose_name='Trạng thái thùng'),
        ),
        migrations.AddField(
            model_name='packingbox',
            name='total_index',
            field=models.FloatField(default=0, verbose_name='Tổng chỉ số đã đóng'),
        ),
        migrations.AddField(
            model_name='packingboxitem',
            name='packing_index',
            field=models.FloatField(default=0, verbose_name='Chỉ số đóng thùng'),
        ),
        migrations.AddField(
            model_name='packingboxitem',
            name='total_index',
            field=models.FloatField(default=0, verbose_name='Tổng chỉ số'),
        ),
    ]
