# Generated by Django 6.0.5 on 2026-05-31 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionitem_lot'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingboxitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_box_items', to='traceability.tracelot', verbose_name='Mã lô truy xuất'),
        ),
    ]
