# Generated by Django 6.0.5 on 2026-06-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đặt mua')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NCC')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Nhà cung cấp')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tài xế')),
                ('vehicle_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phương tiện')),
                ('order_date', models.DateField(verbose_name='Ngày đặt')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Ngày lấy hàng')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập kho')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('assigned_driver', 'Đã giao tài xế'), ('picked_up', 'Đã lấy hàng'), ('waiting_stock_in', 'Chờ nhập kho'), ('received', 'Đã nhập kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=50, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn đặt mua',
                'verbose_name_plural': 'Đơn đặt mua',
                'db_table': 'purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã hoa')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên hoa')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('stems_per_bundle', models.IntegerField(default=50, verbose_name='Quy cách bó')),
                ('ordered_quantity', models.FloatField(default=0, verbose_name='SL đặt')),
                ('received_quantity', models.FloatField(default=0, verbose_name='SL thực nhận')),
                ('expected_bundle_count', models.IntegerField(default=0, verbose_name='Số bó dự kiến')),
                ('actual_bundle_count', models.IntegerField(default=0, verbose_name='Số bó thực tế')),
                ('note', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Chi tiết đặt mua',
                'verbose_name_plural': 'Chi tiết đặt mua',
                'db_table': 'purchase_order_item',
            },
        ),
    ]
