# Generated by Django 6.0.5 on 2026-06-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã đặt mua'),
        ),
    ]
