# Generated by Django 6.0.5 on 2026-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseorder_po_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhân viên tài xế'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_receiver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người nhận kho'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_receiver_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NV nhận kho'),
        ),
    ]
