# Generated by Django 6.0.5 on 2026-06-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_driver_employee_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã chuyến lấy hàng')),
                ('driver_employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NV tài xế')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tài xế')),
                ('vehicle_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phương tiện')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Ngày lấy hàng')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Ngày kho nhận')),
                ('warehouse_receiver_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NV nhận kho')),
                ('warehouse_receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người nhận kho')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('assigned_driver', 'Đã giao tài xế'), ('picked_up', 'Đã lấy hàng'), ('waiting_stock_in', 'Chờ nhập kho'), ('received', 'Đã nhập kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=50, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='purchases.purchaseorder', verbose_name='Đơn đặt mua')),
            ],
            options={
                'verbose_name': 'Chuyến lấy hàng',
                'verbose_name_plural': 'Chuyến lấy hàng',
                'db_table': 'purchase_pickup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePickupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã hoa')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên hoa')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('stems_per_bundle', models.IntegerField(default=50, verbose_name='Quy cách bó')),
                ('planned_quantity', models.FloatField(default=0, verbose_name='SL dự kiến lấy')),
                ('received_quantity', models.FloatField(default=0, verbose_name='SL kho thực nhận')),
                ('planned_bundle_count', models.IntegerField(default=0, verbose_name='Số bó dự kiến')),
                ('actual_bundle_count', models.IntegerField(default=0, verbose_name='Số bó thực nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasepickup', verbose_name='Chuyến lấy hàng')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_items', to='purchases.purchaseorderitem', verbose_name='Sản phẩm đặt mua')),
            ],
            options={
                'verbose_name': 'Chi tiết chuyến lấy hàng',
                'verbose_name_plural': 'Chi tiết chuyến lấy hàng',
                'db_table': 'purchase_pickup_item',
            },
        ),
    ]
