# Generated by Django 6.0.5 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchasepickup_purchasepickupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã NCC dòng hàng'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên NCC dòng hàng'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Chờ tài xế nhận'), ('assigned_driver', 'Đã giao tài xế'), ('waiting_stock_in', 'Chờ nhập kho'), ('received', 'Đã nhập kho'), ('cancelled', 'Hủy đặt hàng')], default='draft', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
