# Generated by Django 6.0.5 on 2026-06-02 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseorderitem_supplier_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giờ đặt'),
        ),
    ]
