# Generated by Django 6.0.5 on 2026-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tài xế chốt dòng'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chốt dòng'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_received_quantity',
            field=models.FloatField(default=0, verbose_name='SL tài xế thực nhận'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='over_quantity_status',
            field=models.CharField(choices=[('none', 'Không vượt'), ('pending', 'Chờ kinh doanh duyệt'), ('approved', 'Kinh doanh đã duyệt'), ('rejected', 'Kinh doanh từ chối')], default='none', max_length=30, verbose_name='Trạng thái vượt SL'),
        ),
    ]
