# Generated by Django 6.0.5 on 2026-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchaseorder_driver_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='driver_confirmed',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='driver_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='over_quantity_status',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='driver_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='driver_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='driver_received_quantity',
            field=models.FloatField(default=0),
        ),
    ]
