# Generated by Django 6.0.5 on 2026-06-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_remove_purchaseorder_driver_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên hoa')),
                ('ordered_quantity', models.FloatField(default=0, verbose_name='SL đặt')),
                ('driver_received_quantity', models.FloatField(default=0, verbose_name='SL tài xế báo nhận')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Nội dung cảnh báo')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt nhận'), ('rejected', 'Không nhận')], default='pending', max_length=30, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='purchases.purchaseorderitem', verbose_name='Dòng sản phẩm')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='purchases.purchaseorder', verbose_name='Đơn đặt mua')),
            ],
            options={
                'verbose_name': 'Cảnh báo đặt mua',
                'verbose_name_plural': 'Cảnh báo đặt mua',
                'db_table': 'purchase_order_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
