# Generated by Django 6.0.5 on 2026-06-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchaseorderalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderalert',
            name='approved_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='SL kinh doanh duyệt'),
        ),
    ]
