# Generated by Django 6.0.5 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchaseorderalert_approved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà cung cấp'),
        ),
    ]
