# Generated by Django 6.0.5 on 2026-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_purchaseorder_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderalert',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tài xế'),
        ),
        migrations.AddField(
            model_name='purchaseorderalert',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà cung cấp'),
        ),
    ]
