# Generated by Django 6.0.5 on 2026-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchaseorderalert_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='over_quantity_status',
            field=models.CharField(choices=[('none', 'Không vượt'), ('pending', 'Chờ duyệt vượt'), ('approved', 'Đã duyệt vượt'), ('rejected', 'Đã điều chỉnh SL')], default='none', max_length=30, verbose_name='Trạng thái vượt SL'),
        ),
    ]
