# Generated by Django 6.0.5 on 2026-06-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_purchaseorderitem_over_quantity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='warehouse_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kho kiểm'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='warehouse_checked_quantity',
            field=models.FloatField(default=0, verbose_name='SL kho kiểm'),
        ),
    ]
