# Generated by Django 6.0.5 on 2026-06-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_purchaseorderitem_warehouse_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseWarehouseCheckDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_quantity', models.FloatField(default=0, verbose_name='SL kho kiểm tạm')),
                ('stems_per_bundle', models.IntegerField(default=50, verbose_name='Quy cách bó tạm')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_check_draft', to='purchases.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Dữ liệu kho kiểm tạm',
                'verbose_name_plural': 'Dữ liệu kho kiểm tạm',
                'db_table': 'purchase_warehouse_check_draft',
            },
        ),
    ]
