# Generated by Django 6.0.5 on 2026-05-28 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái duyệt')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='employees.employee', verbose_name='Nhân viên')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Tài khoản nhân viên',
                'verbose_name_plural': 'Tài khoản nhân viên',
                'db_table': 'accounts_user_employee',
            },
        ),
    ]
