# Generated by Django 6.0.5 on 2026-05-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('can_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Phân quyền module',
                'verbose_name_plural': 'Phân quyền module',
                'db_table': 'accounts_role_module_permission',
                'unique_together': {('group', 'module_name')},
            },
        ),
    ]
