# Generated by Django 6.0.5 on 2026-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolemodulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=100, unique=True)),
                ('module_label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module hệ thống',
                'verbose_name_plural': 'Module hệ thống',
                'db_table': 'accounts_system_module',
                'ordering': ['sort_order', 'module_label'],
            },
        ),
    ]
