# Generated by Django 6.0.5 on 2026-05-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu nhập')),
                ('product_group', models.CharField(choices=[('HH', 'Hoa Hồng'), ('HP', 'Hoa/Lá Phụ'), ('VT', 'Vật Tư')], max_length=10, verbose_name='Nhóm hàng')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhà cung cấp')),
                ('receipt_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-receipt_datetime'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='ĐVT')),
                ('flower_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa')),
                ('quantity', models.FloatField(default=0, verbose_name='Số lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryreceipt', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập kho',
                'verbose_name_plural': 'Chi tiết phiếu nhập kho',
            },
        ),
    ]
