# Generated by Django 6.0.5 on 2026-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=50, verbose_name='Mã giao dịch')),
                ('transaction_type', models.CharField(choices=[('IN', 'Nhập kho'), ('OUT', 'Xuất kho'), ('CHECK', 'Kiểm kê'), ('TRANSFER', 'Điều chuyển'), ('ADJUST', 'Điều chỉnh')], max_length=20, verbose_name='Loại giao dịch')),
                ('warehouse_type', models.CharField(choices=[('RAW', 'Kho nguyên liệu'), ('FINISHED', 'Kho thành phẩm'), ('SALE', 'Kho Sale'), ('MATERIAL', 'Kho vật tư'), ('DAMAGED', 'Kho hư hao')], max_length=20, verbose_name='Kho')),
                ('product_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nhóm hàng')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='ĐVT')),
                ('flower_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa')),
                ('quantity', models.FloatField(default=0, verbose_name='Số lượng')),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã tham chiếu')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type', models.CharField(choices=[('RAW', 'Kho nguyên liệu'), ('FINISHED', 'Kho thành phẩm'), ('SALE', 'Kho Sale'), ('MATERIAL', 'Kho vật tư'), ('DAMAGED', 'Kho hư hao')], max_length=20, verbose_name='Kho')),
                ('product_group', models.CharField(choices=[('HH', 'Hoa Hồng'), ('HP', 'Hoa/Lá Phụ'), ('VT', 'Vật Tư')], max_length=10, verbose_name='Nhóm hàng')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='ĐVT')),
                ('flower_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa')),
                ('quantity', models.FloatField(default=0, verbose_name='Số lượng tồn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'ordering': ['warehouse_type', 'product_group', 'product_name'],
                'unique_together': {('warehouse_type', 'product_group', 'product_code', 'flower_grade')},
            },
        ),
    ]
