# Generated by Django 6.0.5 on 2026-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction_inventorystock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorystock',
            options={'ordering': ['warehouse_type', 'product_group', 'product_name', 'received_date'], 'verbose_name': 'Tồn kho', 'verbose_name_plural': 'Tồn kho'},
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhập gốc'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhập gốc'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('warehouse_type', 'product_group', 'product_code', 'flower_grade', 'supplier_code', 'received_date')},
        ),
    ]
