# Generated by Django 6.0.5 on 2026-05-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorystock_options_and_more'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stocks', to='traceability.tracelot', verbose_name='Mã lô truy xuất'),
        ),
    ]
