# Generated by Django 6.0.5 on 2026-05-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryreceiptitem_lot'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xuất')),
                ('stock_out_type', models.CharField(choices=[('HH', 'Hoa Hồng'), ('HP', 'Hoa/Lá Phụ'), ('DIRECT_SALE', 'Sale trực tiếp'), ('DAMAGED', 'Xuất hoa Hủy')], max_length=30, verbose_name='Loại xuất kho')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhân viên')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhân viên thực hiện')),
                ('employee_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bộ phận')),
                ('employee_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chức vụ')),
                ('stock_out_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ xuất kho')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'ordering': ['-stock_out_datetime'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_stock_id', models.IntegerField(blank=True, null=True, verbose_name='ID tồn kho nguồn')),
                ('source_warehouse', models.CharField(max_length=30, verbose_name='Kho nguồn')),
                ('destination_warehouse', models.CharField(max_length=30, verbose_name='Kho đích')),
                ('product_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nhóm hàng')),
                ('product_code', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='ĐVT')),
                ('original_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa gốc')),
                ('output_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ hoa lúc xuất')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhà cung cấp')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhập gốc')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do Sale/Hủy')),
                ('quantity', models.FloatField(default=0, verbose_name='Số lượng xuất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_items', to='traceability.tracelot', verbose_name='Mã lô truy xuất')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorystockout', verbose_name='Phiếu xuất kho')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu xuất kho',
                'verbose_name_plural': 'Chi tiết phiếu xuất kho',
            },
        ),
    ]
