# Generated by Django 6.0.5 on 2026-06-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorystockout_inventorystockoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='source_po_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã đơn đặt mua liên quan'),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT_LABEL_CREATED', 'Đã tạo QR bó - chờ nhập kho'), ('COMPLETED', 'Đã nhập kho')], default='COMPLETED', max_length=30, verbose_name='Trạng thái phiếu nhập'),
        ),
    ]
