# Generated by Django 6.0.5 on 2026-06-04 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryreceipt_source_po_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ / ngày báo cáo kho'),
        ),
    ]
