# Generated by Django 6.0.5 on 2026-06-04 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryreceipt_business_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-business_date', '-created_at'], 'verbose_name': 'Lịch sử kho', 'verbose_name_plural': 'Lịch sử kho'},
        ),
        migrations.RemoveField(
            model_name='inventoryreceipt',
            name='business_date',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ / ngày báo cáo kho'),
        ),
    ]
