# Generated by Django 6.0.5 on 2026-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã hoa')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hoa')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Loại hoa',
                'verbose_name_plural': 'Danh sách loại hoa',
                'ordering': ['name'],
            },
        ),
    ]
