# Generated by Django 6.0.5 on 2026-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowertype',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xuất xứ'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='processing_loss_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỉ lệ hao hụt sơ chế'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='stem_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CĐ'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DVT'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tone/Nhóm'),
        ),
    ]
