# Generated by Django 6.0.5 on 2026-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_flowertype_origin_flowertype_processing_loss_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowertype',
            name='category_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân Loại'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='processing_loss_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Tỉ lệ hao hụt sơ chế'),
        ),
    ]
