# Generated by Django 6.0.5 on 2026-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_flowertype_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kh', models.CharField(max_length=50, unique=True, verbose_name='Mã KH')),
                ('ten_khach_hang', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('dia_chi', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('sdt', models.CharField(blank=True, max_length=30, null=True, verbose_name='SĐT')),
                ('van_chuyen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vận chuyển')),
                ('vung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vùng')),
                ('nguoi_nhan_thay', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người nhận thay')),
                ('ma_dau', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã đầu')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country V/N')),
                ('phan_loai_kh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phân loại KH')),
                ('ma_so_thue', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
    ]
