# Generated by Django 6.0.5 on 2026-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowertype',
            name='box_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thùng'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='box_weight',
            field=models.FloatField(default=1.4, verbose_name='Trọng lượng thùng'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='bunches_per_box',
            field=models.FloatField(default=0, verbose_name='Số bó/thùng'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='export_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên xuất khẩu'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='nw_per_bunch',
            field=models.FloatField(default=0, verbose_name='NW/bó'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='packing_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quy cách đóng gói'),
        ),
        migrations.AddField(
            model_name='flowertype',
            name='stems_per_bunch',
            field=models.FloatField(default=0, verbose_name='Số cành/bó'),
        ),
    ]
