# Generated by Django 6.0.5 on 2026-05-23 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Khách hàng')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhân viên')),
                ('transport_vehicle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xe vận chuyển')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
                ('status', models.CharField(choices=[('new', 'Mới tạo'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-order_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('flower_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại hoa')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà cung cấp')),
                ('standard_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số lượng tiêu chuẩn')),
                ('sale_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số lượng sale')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='DVT')),
                ('specification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quy cách')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
