# Generated by Django 6.0.5 on 2026-05-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_time', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người tạo đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã khách hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SĐT'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tone/Nhóm'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã sản phẩm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Mới tạo'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flower_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Tên Hoa/Lá phụ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sale_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='standard_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
