# Generated by Django 6.0.5 on 2026-05-31 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='traceability.tracelot', verbose_name='Mã lô truy xuất'),
        ),
    ]
