# Generated by Django 6.0.5 on 2026-05-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên nhà xe')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('receive_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giờ nhận tại xưởng')),
                ('departure_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giờ xe xuất bến')),
                ('receive_type', models.CharField(choices=[('factory', 'Nhận tại xưởng'), ('station', 'Nhận tại bến'), ('other', 'Khác')], default='station', max_length=20, verbose_name='Hình thức nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà xe',
                'verbose_name_plural': 'Nhà xe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên tuyến')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tuyến vận chuyển',
                'verbose_name_plural': 'Tuyến vận chuyển',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Thứ tự ưu tiên')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_routes', to='transport.transportcompany', verbose_name='Nhà xe')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_companies', to='transport.transportroute', verbose_name='Tuyến')),
            ],
            options={
                'verbose_name': 'Nhà xe theo tuyến',
                'verbose_name_plural': 'Nhà xe theo tuyến',
                'ordering': ['route__name', 'priority'],
                'unique_together': {('route', 'company')},
            },
        ),
    ]
