# Generated by Django 6.0.5 on 2026-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='Ngày kiểm tra')),
                ('check_time', models.TimeField(verbose_name='Giờ kiểm tra')),
                ('tire_ok', models.BooleanField(default=False, verbose_name='Lốp xe')),
                ('tire_note', models.TextField(blank=True, null=True)),
                ('box_ok', models.BooleanField(default=False, verbose_name='Thùng xe')),
                ('box_note', models.TextField(blank=True, null=True)),
                ('oil_ok', models.BooleanField(default=False, verbose_name='Nhớt xe')),
                ('oil_note', models.TextField(blank=True, null=True)),
                ('windshield_ok', models.BooleanField(default=False, verbose_name='Kính chắn gió')),
                ('windshield_note', models.TextField(blank=True, null=True)),
                ('fuel_ok', models.BooleanField(default=False, verbose_name='Nhiên liệu trên 95%')),
                ('fuel_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nhiên liệu thực tế')),
                ('fuel_note', models.TextField(blank=True, null=True)),
                ('light_ok', models.BooleanField(default=False, verbose_name='Đèn chiếu sáng')),
                ('light_note', models.TextField(blank=True, null=True)),
                ('horn_ok', models.BooleanField(default=False, verbose_name='Còi')),
                ('horn_note', models.TextField(blank=True, null=True)),
                ('gps_ok', models.BooleanField(default=False, verbose_name='GPS')),
                ('gps_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kiểm tra xe',
                'verbose_name_plural': 'Kiểm tra xe',
                'ordering': ['-created_at'],
            },
        ),
    ]
